// Comprehensive database of real universities worldwide
export interface UniversityData {
  id: string;
  name: string;
  nameRu: string;
  nameKk: string;
  location: string;
  locationRu: string;
  locationKk: string;
  country: string;
  region: 'asia' | 'central-asia' | 'north-america' | 'europe' | 'south-america' | 'oceania';
  rank: number; // World rank
  directions: string[]; // Available programs/directions
  requirements: {
    minGPA: number; // out of 5.0
    minIELTS?: number;
    minSAT?: number;
    minAchievements?: number; // Number of achievements needed
  };
  programs: string[];
  programsRu: string[];
  programsKk: string[];
  tuitionFee?: string; // Annual tuition in USD
  acceptanceRate: number; // Percentage
}

export const UNIVERSITIES_DATABASE: UniversityData[] = [
  // === NORTH AMERICA ===
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    nameRu: 'Массачусетский технологический институт',
    nameKk: 'Массачусетс технологиялық институты',
    location: 'Cambridge, USA',
    locationRu: 'Кембридж, США',
    locationKk: 'Кембридж, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 1,
    directions: ['technology', 'science', 'engineering'],
    requirements: {
      minGPA: 4.8,
      minIELTS: 7.5,
      minSAT: 1520,
      minAchievements: 3,
    },
    programs: ['Computer Science', 'Mechanical Engineering', 'Physics', 'Mathematics'],
    programsRu: ['Компьютерные науки', 'Машиностроение', 'Физика', 'Математика'],
    programsKk: ['Компьютерлік ғылымдар', 'Машина жасау', 'Физика', 'Математика'],
    tuitionFee: '$53,790',
    acceptanceRate: 3.9,
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    nameRu: 'Стэнфордский университет',
    nameKk: 'Стэнфорд университеті',
    location: 'Stanford, USA',
    locationRu: 'Стэнфорд, США',
    locationKk: 'Стэнфорд, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 2,
    directions: ['technology', 'business', 'science', 'engineering'],
    requirements: {
      minGPA: 4.7,
      minIELTS: 7.5,
      minSAT: 1500,
      minAchievements: 3,
    },
    programs: ['Computer Science', 'Business Administration', 'Engineering', 'Bioinformatics'],
    programsRu: ['Компьютерные науки', 'Бизнес-администрирование', 'Инженерия', 'Биоинформатика'],
    programsKk: ['Компьютерлік ғылымдар', 'Бизнес әкімшілік', 'Инженерия', 'Биоинформатика'],
    tuitionFee: '$56,169',
    acceptanceRate: 3.7,
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    nameRu: 'Гарвардский университет',
    nameKk: 'Гарвард университеті',
    location: 'Cambridge, USA',
    locationRu: 'Кембридж, США',
    locationKk: 'Кембридж, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 3,
    directions: ['business', 'law', 'humanities', 'medicine', 'science'],
    requirements: {
      minGPA: 4.7,
      minIELTS: 7.5,
      minSAT: 1510,
      minAchievements: 3,
    },
    programs: ['Law', 'Business', 'Medicine', 'Economics', 'Political Science'],
    programsRu: ['Право', 'Бизнес', 'Медицина', 'Экономика', 'Политология'],
    programsKk: ['Құқық', 'Бизнес', 'Медицина', 'Экономика', 'Саясаттану'],
    tuitionFee: '$54,269',
    acceptanceRate: 3.4,
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    nameRu: 'Калифорнийский технологический институт',
    nameKk: 'Калифорния технологиялық институты',
    location: 'Pasadena, USA',
    locationRu: 'Пасадена, США',
    locationKk: 'Пасадена, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 6,
    directions: ['science', 'engineering', 'technology'],
    requirements: {
      minGPA: 4.6,
      minIELTS: 7.0,
      minSAT: 1530,
      minAchievements: 2,
    },
    programs: ['Physics', 'Chemistry', 'Aerospace Engineering', 'Applied Mathematics'],
    programsRu: ['Физика', 'Химия', 'Аэрокосмическая инженерия', 'Прикладная математика'],
    programsKk: ['Физика', 'Химия', 'Аэроғарыштық инженерия', 'Қолданбалы математика'],
    tuitionFee: '$58,680',
    acceptanceRate: 3.0,
  },
  {
    id: 'berkeley',
    name: 'University of California, Berkeley',
    nameRu: 'Калифорнийский университет в Беркли',
    nameKk: 'Калифорния университеті, Беркли',
    location: 'Berkeley, USA',
    locationRu: 'Беркли, США',
    locationKk: 'Беркли, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 8,
    directions: ['technology', 'science', 'engineering', 'business'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minSAT: 1420,
      minAchievements: 2,
    },
    programs: ['Computer Science', 'Engineering', 'Data Science', 'Business'],
    programsRu: ['Компьютерные науки', 'Инженерия', 'Наука о данных', 'Бизнес'],
    programsKk: ['Компьютерлік ғылымдар', 'Инженерия', 'Деректер ғылымы', 'Бизнес'],
    tuitionFee: '$44,115',
    acceptanceRate: 14.5,
  },
  {
    id: 'toronto',
    name: 'University of Toronto',
    nameRu: 'Университет Торонто',
    nameKk: 'Торонто университеті',
    location: 'Toronto, Canada',
    locationRu: 'Торонто, Канада',
    locationKk: 'Торонто, Канада',
    country: 'Canada',
    region: 'north-america',
    rank: 21,
    directions: ['technology', 'medicine', 'science', 'humanities', 'business'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minSAT: 1350,
      minAchievements: 1,
    },
    programs: ['Computer Science', 'Medicine', 'Engineering', 'Life Sciences'],
    programsRu: ['Компьютерные науки', 'Медицина', 'Инженерия', 'Биологические науки'],
    programsKk: ['Компьютерлік ғылымдар', 'Медицина', 'Инженерия', 'Өмір туралы ғылымдар'],
    tuitionFee: 'CAD $58,160',
    acceptanceRate: 43,
  },

  // === EUROPE ===
  {
    id: 'oxford',
    name: 'University of Oxford',
    nameRu: 'Оксфордский университет',
    nameKk: 'Оксфорд университеті',
    location: 'Oxford, UK',
    locationRu: 'Оксфорд, Великобритания',
    locationKk: 'Оксфорд, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 4,
    directions: ['humanities', 'science', 'law', 'medicine', 'business'],
    requirements: {
      minGPA: 4.6,
      minIELTS: 7.5,
      minAchievements: 2,
    },
    programs: ['Philosophy', 'Law', 'Medicine', 'Economics', 'History'],
    programsRu: ['Философия', 'Право', 'Медицина', 'Экономика', 'История'],
    programsKk: ['Философия', 'Құқық', 'Медицина', 'Экономика', 'Тарих'],
    tuitionFee: '£28,950',
    acceptanceRate: 17.5,
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    nameRu: 'Кембриджский университет',
    nameKk: 'Кембридж университеті',
    location: 'Cambridge, UK',
    locationRu: 'Кембридж, Великобритания',
    locationKk: 'Кембридж, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 5,
    directions: ['science', 'engineering', 'humanities', 'medicine'],
    requirements: {
      minGPA: 4.6,
      minIELTS: 7.5,
      minAchievements: 2,
    },
    programs: ['Natural Sciences', 'Engineering', 'Mathematics', 'Computer Science'],
    programsRu: ['Естественные науки', 'Инженерия', 'Математика', 'Компьютерные науки'],
    programsKk: ['Жаратылыстану ғылымдары', 'Инженерия', 'Математика', 'Компьютерлік ғылымдар'],
    tuitionFee: '£24,789',
    acceptanceRate: 21,
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zurich',
    nameRu: 'ETH Цюрих',
    nameKk: 'ETH Цюрих',
    location: 'Zurich, Switzerland',
    locationRu: 'Цюрих, Швейцария',
    locationKk: 'Цюрих, Швейцария',
    country: 'Switzerland',
    region: 'europe',
    rank: 7,
    directions: ['engineering', 'science', 'technology'],
    requirements: {
      minGPA: 4.5,
      minIELTS: 7.0,
      minAchievements: 2,
    },
    programs: ['Mechanical Engineering', 'Physics', 'Computer Science', 'Architecture'],
    programsRu: ['Машиностроение', 'Физика', 'Компьютерные науки', 'Архитектура'],
    programsKk: ['Машина жасау', 'Физика', 'Компьютерлік ғылымдар', 'Сәулет'],
    tuitionFee: 'CHF 1,298',
    acceptanceRate: 27,
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    nameRu: 'Имперский колледж Лондона',
    nameKk: 'Лондонның Империялық колл��джі',
    location: 'London, UK',
    locationRu: 'Лондон, Великобритания',
    locationKk: 'Лондон, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 9,
    directions: ['science', 'engineering', 'medicine', 'business'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minAchievements: 2,
    },
    programs: ['Engineering', 'Medicine', 'Business', 'Data Science'],
    programsRu: ['Инженерия', 'Медицина', 'Бизнес', 'Наука о данных'],
    programsKk: ['Инженерия', 'Медицина', 'Бизнес', 'Деректер ғылымы'],
    tuitionFee: '£35,100',
    acceptanceRate: 14.3,
  },
  {
    id: 'epfl',
    name: 'EPFL',
    nameRu: 'EPFL (Лозанна)',
    nameKk: 'EPFL (Лозанна)',
    location: 'Lausanne, Switzerland',
    locationRu: 'Лозанна, Швейцария',
    locationKk: 'Лозанна, Швейцария',
    country: 'Switzerland',
    region: 'europe',
    rank: 13,
    directions: ['engineering', 'science', 'technology'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 7.0,
      minAchievements: 1,
    },
    programs: ['Computer Science', 'Life Sciences', 'Engineering', 'Physics'],
    programsRu: ['Компьютерные науки', 'Биологические науки', 'Инженерия', 'Физика'],
    programsKk: ['Компьютерлік ғылымдар', 'Өмір туралы ғылымдар', 'Инженерия', 'Физика'],
    tuitionFee: 'CHF 1,266',
    acceptanceRate: 30,
  },
  {
    id: 'tu-munich',
    name: 'Technical University of Munich',
    nameRu: 'Технический университет Мюнхена',
    nameKk: 'Мюнхен техникалық университеті',
    location: 'Munich, Germany',
    locationRu: 'Мюнхен, Германия',
    locationKk: 'Мюнхен, Германия',
    country: 'Germany',
    region: 'europe',
    rank: 37,
    directions: ['engineering', 'technology', 'science'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'Physics', 'Mathematics'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'Физика', 'Математика'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'Физика', 'Математика'],
    tuitionFee: '€0 (Public)',
    acceptanceRate: 8,
  },

  // === ASIA ===
  {
    id: 'nus',
    name: 'National University of Singapore',
    nameRu: 'Национальный университет Сингапура',
    nameKk: 'Сингапурдың ұлттық университеті',
    location: 'Singapore',
    locationRu: 'Сингапур',
    locationKk: 'Сингапур',
    country: 'Singapore',
    region: 'asia',
    rank: 11,
    directions: ['technology', 'engineering', 'business', 'science'],
    requirements: {
      minGPA: 4.2,
      minIELTS: 6.5,
      minSAT: 1400,
      minAchievements: 1,
    },
    programs: ['Computer Science', 'Business', 'Engineering', 'Medicine'],
    programsRu: ['Компьютерные науки', 'Бизнес', 'Инженерия', 'Медицина'],
    programsKk: ['Компьютерлік ғылымдар', 'Бизнес', 'Инженерия', 'Медицина'],
    tuitionFee: 'SGD $17,550',
    acceptanceRate: 5,
  },
  {
    id: 'tsinghua',
    name: 'Tsinghua University',
    nameRu: 'Университет Цинхуа',
    nameKk: 'Цинхуа университеті',
    location: 'Beijing, China',
    locationRu: 'Пекин, Китай',
    locationKk: 'Пекин, Қытай',
    country: 'China',
    region: 'asia',
    rank: 12,
    directions: ['engineering', 'technology', 'science', 'business'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 6.5,
      minAchievements: 2,
    },
    programs: ['Computer Science', 'Engineering', 'Economics', 'Architecture'],
    programsRu: ['Компьютерные науки', 'Инженерия', 'Экономика', 'Архитектура'],
    programsKk: ['Компьютерлік ғылымдар', 'Инженерия', 'Экономика', 'Сәулет'],
    tuitionFee: '¥30,000',
    acceptanceRate: 2,
  },
  {
    id: 'tokyo',
    name: 'University of Tokyo',
    nameRu: 'Токийский университет',
    nameKk: 'Токио университеті',
    location: 'Tokyo, Japan',
    locationRu: 'Токио, Япония',
    locationKk: 'Токио, Жапония',
    country: 'Japan',
    region: 'asia',
    rank: 23,
    directions: ['science', 'engineering', 'humanities', 'medicine'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Science', 'Medicine', 'Law'],
    programsRu: ['Инженерия', 'Наука', 'Медицина', 'Право'],
    programsKk: ['Инженерия', 'Ғылым', 'Медицина', 'Құқық'],
    tuitionFee: '¥535,800',
    acceptanceRate: 34,
  },
  {
    id: 'seoul',
    name: 'Seoul National University',
    nameRu: 'Сеульский национальный университет',
    nameKk: 'Сеул ұлттық университеті',
    location: 'Seoul, South Korea',
    locationRu: 'Сеул, Южная Корея',
    locationKk: 'Сеул, Оңтүстік Корея',
    country: 'South Korea',
    region: 'asia',
    rank: 29,
    directions: ['engineering', 'business', 'humanities', 'science'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.0,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Business', 'Medicine', 'Liberal Arts'],
    programsRu: ['Инженерия', 'Бизнес', 'Медицина', 'Гуманитарные науки'],
    programsKk: ['Инженерия', 'Бизнес', 'Медицина', 'Гуманитарлық ғылымдар'],
    tuitionFee: '₩4,176,000',
    acceptanceRate: 20,
  },
  {
    id: 'hkust',
    name: 'Hong Kong University of Science and Technology',
    nameRu: 'Гонконгский университет науки и технологий',
    nameKk: 'Гонконг ғылым және технологиялар университеті',
    location: 'Hong Kong',
    locationRu: 'Гонконг',
    locationKk: 'Гонконг',
    country: 'Hong Kong',
    region: 'asia',
    rank: 34,
    directions: ['technology', 'business', 'engineering', 'science'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Computer Science', 'Business', 'Engineering', 'Data Science'],
    programsRu: ['Компьютерные науки', 'Бизнес', 'Инженерия', 'Наука о данных'],
    programsKk: ['Компьютерлік ғылымдар', 'Бизнес', 'Инженерия', 'Деректер ғылымы'],
    tuitionFee: 'HKD $145,000',
    acceptanceRate: 27,
  },

  // === CENTRAL ASIA ===
  {
    id: 'nu',
    name: 'Nazarbayev University',
    nameRu: 'Назарбаев Университет',
    nameKk: 'Назарбаев Университеті',
    location: 'Astana, Kazakhstan',
    locationRu: 'Астана, Казахстан',
    locationKk: 'Астана, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 295,
    directions: ['engineering', 'science', 'business', 'humanities', 'medicine'],
    requirements: {
      minGPA: 3.8,
      minIELTS: 6.0,
      minSAT: 1200,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'Business', 'Medicine', 'Public Policy'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'Бизнес', 'Медицина', 'Государственная политика'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'Бизнес', 'Медицина', 'Мемлекеттік саясат'],
    tuitionFee: 'Free (Scholarship)',
    acceptanceRate: 11,
  },
  {
    id: 'kimep',
    name: 'KIMEP University',
    nameRu: 'Университет КИМЭП',
    nameKk: 'КИМЭП Университеті',
    location: 'Almaty, Kazakhstan',
    locationRu: 'Алматы, Казахстан',
    locationKk: 'Алматы, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 701,
    directions: ['business', 'law', 'humanities'],
    requirements: {
      minGPA: 3.5,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Business Administration', 'Economics', 'Law', 'International Relations'],
    programsRu: ['Бизнес-администрирование', 'Экономика', 'Право', 'Международные отношения'],
    programsKk: ['Бизнес әкімшілік', 'Экономика', 'Құқық', 'Халықаралық қатынастар'],
    tuitionFee: '$6,000',
    acceptanceRate: 40,
  },
  {
    id: 'kbtu',
    name: 'KBTU (Kazakh-British Technical University)',
    nameRu: 'КБТУ (Казахстанско-Британский технический университет)',
    nameKk: 'ҚБТУ (Қазақстан-Британдық техникалық университеті)',
    location: 'Almaty, Kazakhstan',
    locationRu: 'Алматы, Казахстан',
    locationKk: 'Алматы, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 801,
    directions: ['engineering', 'technology', 'business'],
    requirements: {
      minGPA: 3.5,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Petroleum Engineering', 'Computer Science', 'Business', 'Engineering'],
    programsRu: ['Нефтяная инженерия', 'Компьютерные науки', 'Бизнес', 'Инженерия'],
    programsKk: ['Мұнай инженериясы', 'Компьютерлік ғылымдар', 'Бизнес', 'Инженерия'],
    tuitionFee: '$5,500',
    acceptanceRate: 45,
  },

  // === OCEANIA ===
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    nameRu: 'Мельбурнский университет',
    nameKk: 'Мельбурн университеті',
    location: 'Melbourne, Australia',
    locationRu: 'Мельбурн, Австралия',
    locationKk: 'Мельбурн, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 14,
    directions: ['medicine', 'law', 'business', 'science', 'engineering'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Medicine', 'Law', 'Business', 'Engineering', 'Arts'],
    programsRu: ['Медицина', 'Право', 'Бизнес', 'Инженерия', 'Искусство'],
    programsKk: ['Медицина', 'Құқық', 'Бизнес', 'Инженерия', 'Өнер'],
    tuitionFee: 'AUD $44,736',
    acceptanceRate: 70,
  },
  {
    id: 'anu',
    name: 'Australian National University',
    nameRu: 'Австралийский национальный университет',
    nameKk: 'Австралияның ұлттық университеті',
    location: 'Canberra, Australia',
    locationRu: 'Канберра, Австралия',
    locationKk: 'Канберра, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 30,
    directions: ['science', 'humanities', 'engineering', 'law'],
    requirements: {
      minGPA: 3.8,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Science', 'Politics', 'International Relations', 'Engineering'],
    programsRu: ['Наука', 'Политика', 'Международные отношения', 'Инженерия'],
    programsKk: ['Ғылым', 'Саясат', 'Халықаралық қатынастар', 'Инженерия'],
    tuitionFee: 'AUD $45,864',
    acceptanceRate: 35,
  },
  {
    id: 'auckland',
    name: 'University of Auckland',
    nameRu: 'Оклендский университет',
    nameKk: 'Окленд университеті',
    location: 'Auckland, New Zealand',
    locationRu: 'Окленд, Новая Зеландия',
    locationKk: 'Окленд, Жаңа Зеландия',
    country: 'New Zealand',
    region: 'oceania',
    rank: 68,
    directions: ['science', 'engineering', 'business', 'arts'],
    requirements: {
      minGPA: 3.7,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Engineering', 'Business', 'Arts', 'Science'],
    programsRu: ['Инженерия', 'Бизнес', 'Искусство', 'Наука'],
    programsKk: ['Инженерия', 'Бизнес', 'Өнер', 'Ғылым'],
    tuitionFee: 'NZD $32,392',
    acceptanceRate: 60,
  },

  // === SOUTH AMERICA ===
  {
    id: 'usp',
    name: 'University of São Paulo',
    nameRu: 'Университет Сан-Паулу',
    nameKk: 'Сан-Паулу университеті',
    location: 'São Paulo, Brazil',
    locationRu: 'Сан-Паулу, Бразилия',
    locationKk: 'Сан-Паулу, Бразилия',
    country: 'Brazil',
    region: 'south-america',
    rank: 85,
    directions: ['science', 'engineering', 'medicine', 'humanities'],
    requirements: {
      minGPA: 3.5,
      minIELTS: 6.0,
      minAchievements: 0,
    },
    programs: ['Medicine', 'Engineering', 'Biology', 'Law'],
    programsRu: ['Медицина', 'Инженерия', 'Биология', 'Право'],
    programsKk: ['Медицина', 'Инженерия', 'Биология', 'Құқық'],
    tuitionFee: 'Free (Public)',
    acceptanceRate: 3,
  },
  {
    id: 'puc-chile',
    name: 'Pontifical Catholic University of Chile',
    nameRu: 'Папский католический университет Чили',
    nameKk: 'Чилидің папалық католик университеті',
    location: 'Santiago, Chile',
    locationRu: 'Сантьяго, Чили',
    locationKk: 'Сантьяго, Чили',
    country: 'Chile',
    region: 'south-america',
    rank: 135,
    directions: ['engineering', 'business', 'humanities', 'science'],
    requirements: {
      minGPA: 3.5,
      minIELTS: 6.0,
      minAchievements: 0,
    },
    programs: ['Engineering', 'Business', 'Architecture', 'Law'],
    programsRu: ['Инженерия', 'Бизнес', 'Архитектура', 'Право'],
    programsKk: ['Инженерия', 'Бизнес', 'Сәулет', 'Құқық'],
    tuitionFee: '$8,000',
    acceptanceRate: 22,
  },
  
  // === MORE TOP UNIVERSITIES ===
  // North America
  {
    id: 'princeton',
    name: 'Princeton University',
    nameRu: 'Принст��нский университет',
    nameKk: 'Принстон университеті',
    location: 'Princeton, USA',
    locationRu: 'Принстон, США',
    locationKk: 'Принстон, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 10,
    directions: ['humanities', 'science', 'engineering', 'business'],
    requirements: {
      minGPA: 4.7,
      minIELTS: 7.5,
      minSAT: 1500,
      minAchievements: 3,
    },
    programs: ['Computer Science', 'Economics', 'Engineering', 'Physics'],
    programsRu: ['Компьютерные науки', 'Экономика', 'Инженерия', 'Физика'],
    programsKk: ['Компьютерлік ғылымдар', 'Экономика', 'Инженерия', 'Физика'],
    tuitionFee: '$57,410',
    acceptanceRate: 4.4,
  },
  {
    id: 'yale',
    name: 'Yale University',
    nameRu: 'Йельский университет',
    nameKk: 'Йель университеті',
    location: 'New Haven, USA',
    locationRu: 'Нью-Хейвен, США',
    locationKk: 'Нью-Хейвен, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 15,
    directions: ['law', 'humanities', 'business', 'medicine'],
    requirements: {
      minGPA: 4.6,
      minIELTS: 7.0,
      minSAT: 1500,
      minAchievements: 2,
    },
    programs: ['Law', 'Political Science', 'History', 'Medicine'],
    programsRu: ['Право', 'Политология', 'История', 'Медицина'],
    programsKk: ['Құқық', 'Саясаттану', 'Тарих', 'Медицина'],
    tuitionFee: '$62,250',
    acceptanceRate: 4.6,
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    nameRu: 'Колумбийский университет',
    nameKk: 'Колумбия университеті',
    location: 'New York, USA',
    locationRu: 'Нью-Йорк, США',
    locationKk: 'Нью-Йорк, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 18,
    directions: ['business', 'humanities', 'engineering', 'medicine'],
    requirements: {
      minGPA: 4.5,
      minIELTS: 7.0,
      minSAT: 1490,
      minAchievements: 2,
    },
    programs: ['Business', 'Journalism', 'Engineering', 'Medicine'],
    programsRu: ['Бизнес', 'Журналистика', 'Инженерия', 'Медицина'],
    programsKk: ['Бизнес', 'Журналистика', 'Инженерия', 'Медицина'],
    tuitionFee: '$65,524',
    acceptanceRate: 3.9,
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    nameRu: 'Чикагский университет',
    nameKk: 'Чикаго университеті',
    location: 'Chicago, USA',
    locationRu: 'Чикаго, США',
    locationKk: 'Чикаго, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 19,
    directions: ['economics', 'business', 'science', 'humanities'],
    requirements: {
      minGPA: 4.5,
      minIELTS: 7.0,
      minSAT: 1510,
      minAchievements: 2,
    },
    programs: ['Economics', 'Business', 'Physics', 'Law'],
    programsRu: ['Экономика', 'Бизнес', 'Физика', 'Право'],
    programsKk: ['Экономика', 'Бизнес', 'Физика', 'Құқық'],
    tuitionFee: '$62,940',
    acceptanceRate: 5.4,
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    nameRu: 'Корнеллский университет',
    nameKk: 'Корнелл университеті',
    location: 'Ithaca, USA',
    locationRu: 'Итака, США',
    locationKk: 'Итака, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 20,
    directions: ['engineering', 'business', 'science', 'agriculture'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 7.0,
      minSAT: 1470,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Business', 'Hotel Management', 'Agriculture'],
    programsRu: ['Инженерия', 'Бизнес', 'Гостиничный менеджмент', 'Сельское хозяйство'],
    programsKk: ['Инженерия', 'Бизнес', 'Қонақүй менеджменті', 'Ауыл шаруашылығы'],
    tuitionFee: '$63,200',
    acceptanceRate: 7.3,
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania',
    nameRu: 'Университет Пенсильвании',
    nameKk: 'Пенсильвания университеті',
    location: 'Philadelphia, USA',
    locationRu: 'Филадельфия, США',
    locationKk: 'Филадельфия, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 16,
    directions: ['business', 'medicine', 'engineering', 'law'],
    requirements: {
      minGPA: 4.6,
      minIELTS: 7.5,
      minSAT: 1500,
      minAchievements: 2,
    },
    programs: ['Wharton Business', 'Medicine', 'Engineering', 'Law'],
    programsRu: ['Wharton Бизнес', 'Медицина', 'Инженерия', 'Право'],
    programsKk: ['Wharton Бизнес', 'Медицина', 'Инженерия', 'Құқық'],
    tuitionFee: '$63,452',
    acceptanceRate: 5.9,
  },
  {
    id: 'duke',
    name: 'Duke University',
    nameRu: 'Университет Дьюка',
    nameKk: 'Дьюк университеті',
    location: 'Durham, USA',
    locationRu: 'Дарем, США',
    locationKk: 'Дарем, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 25,
    directions: ['medicine', 'business', 'engineering', 'law'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minSAT: 1510,
      minAchievements: 2,
    },
    programs: ['Medicine', 'Business', 'Engineering', 'Public Policy'],
    programsRu: ['Медицина', 'Бизнес', 'Инженерия', 'Государственная политика'],
    programsKk: ['Медицина', 'Бизнес', 'Инженерия', 'Мемлекеттік саясат'],
    tuitionFee: '$63,450',
    acceptanceRate: 6.2,
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    nameRu: 'Университет Британской Колумбии',
    nameKk: 'Британ Колумбиясы университеті',
    location: 'Vancouver, Canada',
    locationRu: 'Ванкувер, Канада',
    locationKk: 'Ванкувер, Канада',
    country: 'Canada',
    region: 'north-america',
    rank: 35,
    directions: ['science', 'engineering', 'business', 'arts'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minSAT: 1320,
      minAchievements: 1,
    },
    programs: ['Computer Science', 'Engineering', 'Business', 'Medicine'],
    programsRu: ['Компьютерные науки', 'Инженерия', 'Бизнес', 'Медицина'],
    programsKk: ['Компьютерлік ғылымдар', 'Инженерия', 'Бизнес', 'Медицина'],
    tuitionFee: 'CAD $42,802',
    acceptanceRate: 52,
  },
  {
    id: 'mcgill',
    name: 'McGill University',
    nameRu: 'Университет МакГилл',
    nameKk: 'МакГилл университеті',
    location: 'Montreal, Canada',
    locationRu: 'Монреаль, Канада',
    locationKk: 'Монреаль, Канада',
    country: 'Canada',
    region: 'north-america',
    rank: 31,
    directions: ['medicine', 'science', 'engineering', 'law'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Medicine', 'Engineering', 'Law', 'Science'],
    programsRu: ['Медицина', 'Инженерия', 'Право', 'Наука'],
    programsKk: ['Медицина', 'Инженерия', 'Құқық', 'Ғылым'],
    tuitionFee: 'CAD $24,294',
    acceptanceRate: 46,
  },

  // Europe  
  {
    id: 'ucl',
    name: 'University College London',
    nameRu: 'Университетский колледж Лондона',
    nameKk: 'Лондон университет колледжі',
    location: 'London, UK',
    locationRu: 'Лондон, Великобритания',
    locationKk: 'Лондон, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 10,
    directions: ['science', 'medicine', 'engineering', 'humanities'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minAchievements: 2,
    },
    programs: ['Medicine', 'Engineering', 'Computer Science', 'Law'],
    programsRu: ['Медицина', 'Инженерия', 'Компьютерные науки', 'Право'],
    programsKk: ['Медицина', 'Инженерия', 'Компьютерлік ғылымдар', 'Құқық'],
    tuitionFee: '£28,500',
    acceptanceRate: 48,
  },
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    nameRu: 'Эдинбургский университет',
    nameKk: 'Эдинбург университеті',
    location: 'Edinburgh, UK',
    locationRu: 'Эдинбург, Великобритания',
    locationKk: 'Эдинбург, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 22,
    directions: ['science', 'medicine', 'arts', 'engineering'],
    requirements: {
      minGPA: 4.2,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Medicine', 'AI', 'Law', 'Business'],
    programsRu: ['Медицина', 'Искусственный интеллект', 'Право', 'Бизнес'],
    programsKk: ['Медицина', 'Жасанды интеллект', 'Құқық', 'Бизнес'],
    tuitionFee: '£34,800',
    acceptanceRate: 40,
  },
  {
    id: 'lse',
    name: 'London School of Economics',
    nameRu: 'Лондонская школа экономики',
    nameKk: 'Лондон экономика мектебі',
    location: 'London, UK',
    locationRu: 'Лондон, Великобритания',
    locationKk: 'Лондон, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 45,
    directions: ['economics', 'business', 'law', 'humanities'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 7.0,
      minAchievements: 1,
    },
    programs: ['Economics', 'Finance', 'Law', 'Political Science'],
    programsRu: ['Экономика', 'Финансы', 'Право', 'Политология'],
    programsKk: ['Экономика', 'Қаржы', 'Құқық', 'Саясаттану'],
    tuitionFee: '£25,392',
    acceptanceRate: 8.9,
  },
  {
    id: 'kaist',
    name: 'KAIST',
    nameRu: 'KAIST (Корея)',
    nameKk: 'KAIST (Корея)',
    location: 'Daejeon, South Korea',
    locationRu: 'Тэджон, Южная Корея',
    locationKk: 'Тэджон, Оңтүстік Корея',
    country: 'South Korea',
    region: 'asia',
    rank: 56,
    directions: ['engineering', 'technology', 'science'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'AI', 'Robotics'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'ИИ', 'Робототехника'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'ЖИ', 'Робототехника'],
    tuitionFee: '₩9,680,000',
    acceptanceRate: 15,
  },
  {
    id: 'peking',
    name: 'Peking University',
    nameRu: 'Пекинский университет',
    nameKk: 'Пекин университеті',
    location: 'Beijing, China',
    locationRu: 'Пекин, Китай',
    locationKk: 'Пекин, Қытай',
    country: 'China',
    region: 'asia',
    rank: 17,
    directions: ['science', 'humanities', 'engineering', 'business'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 6.5,
      minAchievements: 2,
    },
    programs: ['Computer Science', 'Economics', 'Law', 'Medicine'],
    programsRu: ['Компьютерные науки', 'Экономика', 'Право', 'Медицина'],
    programsKk: ['Компьютерлік ғылымдар', 'Экономика', 'Құқық', 'Медицина'],
    tuitionFee: '¥26,000',
    acceptanceRate: 1.5,
  },
  {
    id: 'ntu',
    name: 'Nanyang Technological University',
    nameRu: 'Наньянский технологический университет',
    nameKk: 'Наньян технологиялық университеті',
    location: 'Singapore',
    locationRu: 'Сингапур',
    locationKk: 'Сингапур',
    country: 'Singapore',
    region: 'asia',
    rank: 26,
    directions: ['engineering', 'technology', 'business', 'science'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'Business', 'Media'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'Бизнес', 'Медиа'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'Бизнес', 'Медиа'],
    tuitionFee: 'SGD $18,150',
    acceptanceRate: 10,
  },
  {
    id: 'sydney',
    name: 'University of Sydney',
    nameRu: 'Сиднейский университет',
    nameKk: 'Сидней университеті',
    location: 'Sydney, Australia',
    locationRu: 'Сидней, Австралия',
    locationKk: 'Сидней, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 41,
    directions: ['medicine', 'law', 'business', 'engineering'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Medicine', 'Law', 'Business', 'Engineering'],
    programsRu: ['Медицина', 'Право', 'Бизнес', 'Инженерия'],
    programsKk: ['Медицина', 'Құқық', 'Бизнес', 'Инженерия'],
    tuitionFee: 'AUD $52,500',
    acceptanceRate: 30,
  },
  {
    id: 'queensland',
    name: 'University of Queensland',
    nameRu: 'Университет Квинсленда',
    nameKk: 'Квинсленд университеті',
    location: 'Brisbane, Australia',
    locationRu: 'Брисбен, Австралия',
    locationKk: 'Брисбен, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 50,
    directions: ['science', 'engineering', 'medicine', 'business'],
    requirements: {
      minGPA: 3.8,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Science', 'Engineering', 'Medicine', 'Business'],
    programsRu: ['Наука', 'Инженерия', 'Медицина', 'Бизнес'],
    programsKk: ['Ғылым', 'Инженерия', 'Медицина', 'Бизнес'],
    tuitionFee: 'AUD $45,120',
    acceptanceRate: 55,
  },
  
  // === MORE USA UNIVERSITIES (TOP 200) ===
  {
    id: 'ucla',
    name: 'University of California, Los Angeles',
    nameRu: 'Калифорнийский университет в Лос-Анджелесе',
    nameKk: 'Лос-Анджелес Калифорния университеті',
    location: 'Los Angeles, USA',
    locationRu: 'Лос-Анджелес, США',
    locationKk: 'Лос-Анджелес, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 14,
    directions: ['medicine', 'engineering', 'arts', 'business'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minSAT: 1440,
      minAchievements: 2,
    },
    programs: ['Medicine', 'Film', 'Engineering', 'Business'],
    programsRu: ['Медицина', 'Кино', 'Инженерия', 'Бизнес'],
    programsKk: ['Медицина', 'Кино', 'Инженерия', 'Бизнес'],
    tuitionFee: '$43,500',
    acceptanceRate: 10.8,
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    nameRu: 'Северо-Западный университет',
    nameKk: 'Солтүстік-Батыс университеті',
    location: 'Evanston, USA',
    locationRu: 'Эванстон, США',
    locationKk: 'Эванстон, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 24,
    directions: ['journalism', 'business', 'engineering', 'medicine'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minSAT: 1490,
      minAchievements: 2,
    },
    programs: ['Journalism', 'Business', 'Engineering', 'Medicine'],
    programsRu: ['Журналистика', 'Бизнес', 'Инженерия', 'Медицина'],
    programsKk: ['Журналистика', 'Бизнес', 'Инженерия', 'Медицина'],
    tuitionFee: '$63,468',
    acceptanceRate: 7.0,
  },
  {
    id: 'nyu',
    name: 'New York University',
    nameRu: 'Нью-Йоркский университет',
    nameKk: 'Нью-Йорк университеті',
    location: 'New York, USA',
    locationRu: 'Нью-Йорк, США',
    locationKk: 'Нью-Йорк, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 38,
    directions: ['business', 'arts', 'law', 'medicine'],
    requirements: {
      minGPA: 4.2,
      minIELTS: 7.0,
      minSAT: 1470,
      minAchievements: 1,
    },
    programs: ['Business', 'Film', 'Law', 'Medicine'],
    programsRu: ['Бизнес', 'Кино', 'Право', 'Медицина'],
    programsKk: ['Бизнес', 'Кино', 'Құқық', 'Медицина'],
    tuitionFee: '$58,168',
    acceptanceRate: 12.8,
  },
  {
    id: 'michigan',
    name: 'University of Michigan',
    nameRu: 'Мичиганский университет',
    nameKk: 'Мичиган университеті',
    location: 'Ann Arbor, USA',
    locationRu: 'Анн-Арбор, США',
    locationKk: 'Анн-Арбор, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 23,
    directions: ['engineering', 'business', 'medicine', 'law'],
    requirements: {
      minGPA: 4.2,
      minIELTS: 7.0,
      minSAT: 1450,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Business', 'Medicine', 'Law'],
    programsRu: ['Инженерия', 'Бизнес', 'Медицина', 'Право'],
    programsKk: ['Инженерия', 'Бизнес', 'Медицина', 'Құқық'],
    tuitionFee: '$53,232',
    acceptanceRate: 18.0,
  },
  {
    id: 'carnegie-mellon',
    name: 'Carnegie Mellon University',
    nameRu: 'Университет Карнеги-Меллон',
    nameKk: 'Карнеги-Меллон университеті',
    location: 'Pittsburgh, USA',
    locationRu: 'Питтсбург, США',
    locationKk: 'Питтсбург, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 28,
    directions: ['technology', 'engineering', 'business', 'arts'],
    requirements: {
      minGPA: 4.3,
      minIELTS: 7.5,
      minSAT: 1510,
      minAchievements: 2,
    },
    programs: ['Computer Science', 'Robotics', 'AI', 'Drama'],
    programsRu: ['Компьютерные науки', 'Робототехника', 'ИИ', 'Драма'],
    programsKk: ['Компьютерлік ғылымдар', 'Робототехника', 'ЖИ', 'Драма'],
    tuitionFee: '$61,344',
    acceptanceRate: 11.3,
  },
  {
    id: 'uc-san-diego',
    name: 'University of California, San Diego',
    nameRu: 'Калифорнийский университет в Сан-Диего',
    nameKk: 'Сан-Диего Калифорния университеті',
    location: 'San Diego, USA',
    locationRu: 'Сан-Диего, США',
    locationKk: 'Сан-Диего, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 34,
    directions: ['science', 'engineering', 'medicine', 'business'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 7.0,
      minSAT: 1400,
      minAchievements: 1,
    },
    programs: ['Bioengineering', 'Computer Science', 'Medicine', 'Business'],
    programsRu: ['Биоинженерия', 'Компьютерные науки', 'Медицина', 'Бизнес'],
    programsKk: ['Биоинженерия', 'Компьютерлік ғылымдар', 'Медицина', 'Бизнес'],
    tuitionFee: '$44,500',
    acceptanceRate: 30.2,
  },
  {
    id: 'brown',
    name: 'Brown University',
    nameRu: 'Университет Брауна',
    nameKk: 'Браун университеті',
    location: 'Providence, USA',
    locationRu: 'Провиденс, США',
    locationKk: 'Провиденс, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 60,
    directions: ['humanities', 'science', 'engineering', 'medicine'],
    requirements: {
      minGPA: 4.4,
      minIELTS: 7.0,
      minSAT: 1500,
      minAchievements: 2,
    },
    programs: ['Liberal Arts', 'Medicine', 'Engineering', 'Computer Science'],
    programsRu: ['Гуманитарные науки', 'Медицина', 'Инженерия', 'Информатика'],
    programsKk: ['Гуманитарлық ғылымдар', 'Медицина', 'Инженерия', 'Информатика'],
    tuitionFee: '$65,146',
    acceptanceRate: 5.0,
  },

  // === MORE EUROPE UNIVERSITIES ===
  {
    id: 'heidelberg',
    name: 'Heidelberg University',
    nameRu: 'Гейдельбергский университет',
    nameKk: 'Гейдельберг университеті',
    location: 'Heidelberg, Germany',
    locationRu: 'Гейдельберг, Германия',
    locationKk: 'Гейдельберг, Германия',
    country: 'Germany',
    region: 'europe',
    rank: 64,
    directions: ['medicine', 'science', 'law', 'humanities'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Medicine', 'Law', 'Biology', 'Physics'],
    programsRu: ['Медицина', 'Право', 'Биология', 'Физика'],
    programsKk: ['Медицина', 'Құқық', 'Биология', 'Физика'],
    tuitionFee: '€3,000',
    acceptanceRate: 25,
  },
  {
    id: 'munich',
    name: 'Technical University of Munich',
    nameRu: 'Технический университет Мюнхена',
    nameKk: 'Мюнхен техникалық университеті',
    location: 'Munich, Germany',
    locationRu: 'Мюнхен, Германия',
    locationKk: 'Мюнхен, Германия',
    country: 'Germany',
    region: 'europe',
    rank: 37,
    directions: ['engineering', 'technology', 'science', 'business'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'Physics', 'Business'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'Физика', 'Бизнес'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'Физика', 'Бизнес'],
    tuitionFee: '€3,500',
    acceptanceRate: 8,
  },
  {
    id: 'sorbonne',
    name: 'Sorbonne University',
    nameRu: 'Университет Сорбонна',
    nameKk: 'Сорбонна университеті',
    location: 'Paris, France',
    locationRu: 'Париж, Франция',
    locationKk: 'Париж, Франция',
    country: 'France',
    region: 'europe',
    rank: 44,
    directions: ['humanities', 'science', 'medicine', 'arts'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Humanities', 'Medicine', 'Science', 'Arts'],
    programsRu: ['Гуманитарные науки', 'Медицина', 'Наука', 'Искусство'],
    programsKk: ['Гуманитарлық ғылымдар', 'Медицина', 'Ғылым', 'Өнер'],
    tuitionFee: '€2,770',
    acceptanceRate: 32,
  },
  {
    id: 'delft',
    name: 'Delft University of Technology',
    nameRu: 'Делфтский технический университет',
    nameKk: 'Делфт техникалық университеті',
    location: 'Delft, Netherlands',
    locationRu: 'Делфт, Нидерланды',
    locationKk: 'Делфт, Нидерланды',
    country: 'Netherlands',
    region: 'europe',
    rank: 54,
    directions: ['engineering', 'technology', 'science', 'design'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Architecture', 'Computer Science', 'Design'],
    programsRu: ['Инженерия', 'Архитектура', 'Информатика', 'Дизайн'],
    programsKk: ['Инженерия', 'Сәулет', 'Информатика', 'Дизайн'],
    tuitionFee: '€18,750',
    acceptanceRate: 50,
  },
  {
    id: 'amsterdam',
    name: 'University of Amsterdam',
    nameRu: 'Амстердамский университет',
    nameKk: 'Амстердам университеті',
    location: 'Amsterdam, Netherlands',
    locationRu: 'Амстердам, Нидерланды',
    locationKk: 'Амстердам, Нидерланды',
    country: 'Netherlands',
    region: 'europe',
    rank: 58,
    directions: ['business', 'humanities', 'science', 'law'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Business', 'Law', 'Psychology', 'Science'],
    programsRu: ['Бизнес', 'Право', 'Психология', 'Наука'],
    programsKk: ['Бизнес', 'Құқық', 'Психология', 'Ғылым'],
    tuitionFee: '€12,500',
    acceptanceRate: 55,
  },
  {
    id: 'copenhagen',
    name: 'University of Copenhagen',
    nameRu: 'Копенгагенский университет',
    nameKk: 'Копенгаген университеті',
    location: 'Copenhagen, Denmark',
    locationRu: 'Копенгаген, Дания',
    locationKk: 'Копенгаген, Дания',
    country: 'Denmark',
    region: 'europe',
    rank: 82,
    directions: ['medicine', 'science', 'law', 'humanities'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Medicine', 'Biology', 'Law', 'Science'],
    programsRu: ['Медицина', 'Биология', 'Право', 'Наука'],
    programsKk: ['Медицина', 'Биология', 'Құқық', 'Ғылым'],
    tuitionFee: '€15,000',
    acceptanceRate: 45,
  },
  {
    id: 'kings-college',
    name: "King's College London",
    nameRu: 'Королевский колледж Лондона',
    nameKk: 'Лондон корольдік колледжі',
    location: 'London, UK',
    locationRu: 'Лондон, Великобритания',
    locationKk: 'Лондон, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 40,
    directions: ['medicine', 'law', 'humanities', 'science'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 7.0,
      minAchievements: 1,
    },
    programs: ['Medicine', 'Law', 'Dentistry', 'Psychology'],
    programsRu: ['Медицина', 'Право', 'Стоматология', 'Психология'],
    programsKk: ['Медицина', 'Құқық', 'Стоматология', 'Психология'],
    tuitionFee: '£32,000',
    acceptanceRate: 13,
  },
  {
    id: 'manchester',
    name: 'University of Manchester',
    nameRu: 'Манчестерский университет',
    nameKk: 'Манчестер университеті',
    location: 'Manchester, UK',
    locationRu: 'Манчестер, Великобритания',
    locationKk: 'Манчестер, Ұлыбритания',
    country: 'UK',
    region: 'europe',
    rank: 27,
    directions: ['engineering', 'science', 'business', 'medicine'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Computer Science', 'Business', 'Medicine'],
    programsRu: ['Инженерия', 'Компьютерные науки', 'Бизнес', 'Медицина'],
    programsKk: ['Инженерия', 'Компьютерлік ғылымдар', 'Бизнес', 'Медицина'],
    tuitionFee: '£28,000',
    acceptanceRate: 56,
  },

  // === MORE ASIA UNIVERSITIES ===
  {
    id: 'hku',
    name: 'University of Hong Kong',
    nameRu: 'Гонконгский университет',
    nameKk: 'Гонконг университеті',
    location: 'Hong Kong',
    locationRu: 'Гонконг',
    locationKk: 'Гонконг',
    country: 'Hong Kong',
    region: 'asia',
    rank: 26,
    directions: ['business', 'medicine', 'law', 'engineering'],
    requirements: {
      minGPA: 4.1,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Business', 'Medicine', 'Law', 'Engineering'],
    programsRu: ['Бизнес', 'Медицина', 'Право', 'Инженерия'],
    programsKk: ['Бизнес', 'Медицина', 'Құқық', 'Инженерия'],
    tuitionFee: 'HKD $171,000',
    acceptanceRate: 10,
  },
  {
    id: 'kyoto',
    name: 'Kyoto University',
    nameRu: 'Киотский университет',
    nameKk: 'Киото университеті',
    location: 'Kyoto, Japan',
    locationRu: 'Киото, Япония',
    locationKk: 'Киото, Жапония',
    country: 'Japan',
    region: 'asia',
    rank: 36,
    directions: ['science', 'engineering', 'medicine', 'humanities'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.0,
      minAchievements: 1,
    },
    programs: ['Science', 'Engineering', 'Medicine', 'Humanities'],
    programsRu: ['Наука', 'Инженерия', 'Медицина', 'Гуманитарные науки'],
    programsKk: ['Ғылым', 'Инженерия', 'Медицина', 'Гуманитарлық ғылымдар'],
    tuitionFee: '¥535,800',
    acceptanceRate: 15,
  },
  {
    id: 'fudan',
    name: 'Fudan University',
    nameRu: 'Университет Фудань',
    nameKk: 'Фудань университеті',
    location: 'Shanghai, China',
    locationRu: 'Шанхай, Китай',
    locationKk: 'Шанхай, Қытай',
    country: 'China',
    region: 'asia',
    rank: 50,
    directions: ['business', 'science', 'medicine', 'engineering'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Business', 'Medicine', 'Engineering', 'Computer Science'],
    programsRu: ['Бизнес', 'Медицина', 'Инженерия', 'Компьютерные науки'],
    programsKk: ['Бизнес', 'Медицина', 'Инженерия', 'Компьютерлік ғылымдар'],
    tuitionFee: '¥25,000',
    acceptanceRate: 3,
  },
  {
    id: 'postech',
    name: 'POSTECH',
    nameRu: 'POSTECH (Корея)',
    nameKk: 'POSTECH (Корея)',
    location: 'Pohang, South Korea',
    locationRu: 'Пхохан, Южная Корея',
    locationKk: 'Пхохан, Оңтүстік Корея',
    country: 'South Korea',
    region: 'asia',
    rank: 71,
    directions: ['engineering', 'science', 'technology'],
    requirements: {
      minGPA: 4.0,
      minIELTS: 6.0,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Physics', 'Chemistry', 'Computer Science'],
    programsRu: ['Инженерия', '��изика', 'Химия', 'Компьютерные науки'],
    programsKk: ['Инженерия', 'Физика', 'Химия', 'Компьютерлік ғылымдар'],
    tuitionFee: '₩8,200,000',
    acceptanceRate: 12,
  },

  // === MORE CANADA & OCEANIA & CENTRAL ASIA ===
  {
    id: 'waterloo',
    name: 'University of Waterloo',
    nameRu: 'Университет Ватерлоо',
    nameKk: 'Ватерлоо университеті',
    location: 'Waterloo, Canada',
    locationRu: 'Ватерлоо, Канада',
    locationKk: 'Ватерлоо, Канада',
    country: 'Canada',
    region: 'north-america',
    rank: 112,
    directions: ['engineering', 'technology', 'business', 'science'],
    requirements: {
      minGPA: 3.8,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Computer Science', 'Engineering', 'Business', 'Math'],
    programsRu: ['Компьютерные науки', 'Инженерия', 'Бизнес', 'Математика'],
    programsKk: ['Компьютерлік ғылымдар', 'Инженерия', 'Бизнес', 'Математика'],
    tuitionFee: 'CAD $50,000',
    acceptanceRate: 53,
  },
  {
    id: 'unsw',
    name: 'University of New South Wales',
    nameRu: 'Университет Нового Южного Уэльса',
    nameKk: 'Жаңа Оңтүстік Уэльс университеті',
    location: 'Sydney, Australia',
    locationRu: 'Сидней, Австралия',
    locationKk: 'Сидней, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 43,
    directions: ['engineering', 'business', 'science', 'law'],
    requirements: {
      minGPA: 3.9,
      minIELTS: 6.5,
      minAchievements: 1,
    },
    programs: ['Engineering', 'Business', 'Computer Science', 'Law'],
    programsRu: ['Инженерия', 'Бизнес', 'Компьютерные науки', 'Право'],
    programsKk: ['Инженерия', 'Бизнес', 'Компьютерлік ғылымдар', 'Құқық'],
    tuitionFee: 'AUD $48,000',
    acceptanceRate: 35,
  },
  {
    id: 'monash',
    name: 'Monash University',
    nameRu: 'Университет Монаш',
    nameKk: 'Монаш университеті',
    location: 'Melbourne, Australia',
    locationRu: 'Мельбурн, Австралия',
    locationKk: 'Мельбурн, Австралия',
    country: 'Australia',
    region: 'oceania',
    rank: 42,
    directions: ['business', 'engineering', 'medicine', 'science'],
    requirements: {
      minGPA: 3.8,
      minIELTS: 6.5,
      minAchievements: 0,
    },
    programs: ['Business', 'Engineering', 'Medicine', 'Pharmacy'],
    programsRu: ['Бизнес', 'Инженерия', '��едицина', 'Фармацевтика'],
    programsKk: ['Бизнес', 'Инженерия', 'Медицина', 'Фармацевтика'],
    tuitionFee: 'AUD $45,000',
    acceptanceRate: 40,
  },
  {
    id: 'enu',
    name: 'Eurasian National University',
    nameRu: 'Евразийский национальный университет',
    nameKk: 'Еуразия ұлттық университеті',
    location: 'Astana, Kazakhstan',
    locationRu: 'Астана, Казахстан',
    locationKk: 'Астана, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 651,
    directions: ['humanities', 'law', 'education', 'science'],
    requirements: {
      minGPA: 3.3,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Law', 'Education', 'History', 'Economics'],
    programsRu: ['Право', 'Образование', 'История', 'Экономика'],
    programsKk: ['Құқық', 'Білім беру', 'Тарих', 'Экономика'],
    tuitionFee: '₸1,200,000',
    acceptanceRate: 65,
  },
  {
    id: 'kaznmu',
    name: 'Kazakh National Medical University',
    nameRu: 'КазНМУ им. Асфендиярова',
    nameKk: 'Асфендияров атындағы ҚазҰМУ',
    location: 'Almaty, Kazakhstan',
    locationRu: 'Алматы, Казахстан',
    locationKk: 'Алматы, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 701,
    directions: ['medicine', 'pharmacy', 'science'],
    requirements: {
      minGPA: 3.5,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Medicine', 'Pharmacy', 'Dentistry', 'Nursing'],
    programsRu: ['Медицина', 'Фармацевтика', 'Стоматология', 'Сестринское дело'],
    programsKk: ['Медицина', 'Фармацевтика', 'Стоматология', 'Мейірбике ісі'],
    tuitionFee: '₸1,500,000',
    acceptanceRate: 55,
  },
  {
    id: 'narxoz',
    name: 'Narxoz University',
    nameRu: 'Университет Нархоз',
    nameKk: 'Нархоз университеті',
    location: 'Almaty, Kazakhstan',
    locationRu: 'Алматы, Казахстан',
    locationKk: 'Алматы, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 851,
    directions: ['business', 'economics', 'law'],
    requirements: {
      minGPA: 3.2,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Business', 'Economics', 'Finance', 'Marketing'],
    programsRu: ['Бизнес', 'Экономика', 'Финансы', 'Маркетинг'],
    programsKk: ['Бизнес', 'Экономика', 'Қаржы', 'Маркет��нг'],
    tuitionFee: '₸1,800,000',
    acceptanceRate: 70,
  },
  // === ACCESSIBLE UNIVERSITIES (Lower Requirements) ===
  {
    id: 'arizona-state',
    name: 'Arizona State University',
    nameRu: 'Университет штата Аризона',
    nameKk: 'Аризона мемлекеттік университеті',
    location: 'Phoenix, USA',
    locationRu: 'Финикс, США',
    locationKk: 'Финикс, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 216,
    directions: ['business', 'engineering', 'technology', 'arts'],
    requirements: {
      minGPA: 2.5,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Business', 'Engineering', 'Computer Science', 'Design'],
    programsRu: ['Бизнес', 'Инженерия', 'Информатика', 'Дизайн'],
    programsKk: ['Бизнес', 'Инженерия', 'Информатика', 'Дизайн'],
    tuitionFee: '$28,800',
    acceptanceRate: 88,
  },
  {
    id: 'csun',
    name: 'California State University, Northridge',
    nameRu: 'Калифорнийский государственный университет в Нортридже',
    nameKk: 'Нортридж Калифорния мемлекеттік университеті',
    location: 'Los Angeles, USA',
    locationRu: 'Лос-Анджелес, США',
    locationKk: 'Лос-Анджелес, АҚШ',
    country: 'USA',
    region: 'north-america',
    rank: 601,
    directions: ['business', 'arts', 'engineering', 'humanities'],
    requirements: {
      minGPA: 2.5,
      minIELTS: 6.0,
      minAchievements: 0,
    },
    programs: ['Business', 'Film', 'Engineering', 'Music'],
    programsRu: ['Бизнес', 'Кино', 'Инженерия', 'Музыка'],
    programsKk: ['Бизнес', 'Кино', 'Инженерия', 'Музыка'],
    tuitionFee: '$16,896',
    acceptanceRate: 91,
  },
  {
    id: 'umu',
    name: 'Umea University',
    nameRu: 'Университет Умео',
    nameKk: 'Умео университеті',
    location: 'Umea, Sweden',
    locationRu: 'Умео, Швеция',
    locationKk: 'Умео, Швеция',
    country: 'Sweden',
    region: 'europe',
    rank: 286,
    directions: ['science', 'engineering', 'medicine', 'business'],
    requirements: {
      minGPA: 2.8,
      minIELTS: 6.0,
      minAchievements: 0,
    },
    programs: ['Environmental Science', 'Engineering', 'Medicine', 'Business'],
    programsRu: ['Экология', 'Инженерия', 'Медицина', 'Бизнес'],
    programsKk: ['Экология', 'Инженерия', 'Медицина', 'Бизнес'],
    tuitionFee: 'Free (EU), €14,000 (Non-EU)',
    acceptanceRate: 75,
  },
  {
    id: 'uoa-auckland-tech',
    name: 'Auckland University of Technology',
    nameRu: 'Технологический университет Окленда',
    nameKk: 'Окленд технологиялық университеті',
    location: 'Auckland, New Zealand',
    locationRu: 'Окленд, Новая Зеландия',
    locationKk: 'Окленд, Жаңа Зеландия',
    country: 'New Zealand',
    region: 'oceania',
    rank: 407,
    directions: ['technology', 'engineering', 'business', 'arts'],
    requirements: {
      minGPA: 2.7,
      minIELTS: 6.0,
      minAchievements: 0,
    },
    programs: ['Computer Science', 'Engineering', 'Business', 'Design'],
    programsRu: ['Информатика', 'Инженерия', 'Бизнес', 'Дизайн'],
    programsKk: ['Информатика', 'Инженерия', 'Бизнес', 'Дизайн'],
    tuitionFee: 'NZ$32,000',
    acceptanceRate: 80,
  },
  {
    id: 'ntu-singapore-poly',
    name: 'Singapore Polytechnic',
    nameRu: 'Сингапурский политехнический университет',
    nameKk: 'Сингапур политехникалық университеті',
    location: 'Singapore',
    locationRu: 'Сингапур',
    locationKk: 'Сингапур',
    country: 'Singapore',
    region: 'asia',
    rank: 551,
    directions: ['engineering', 'technology', 'business'],
    requirements: {
      minGPA: 2.6,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Engineering', 'IT', 'Business', 'Media'],
    programsRu: ['Инженерия', 'ИТ', 'Бизнес', 'Медиа'],
    programsKk: ['Инженерия', 'ИТ', 'Бизнес', 'Медиа'],
    tuitionFee: 'S$15,000',
    acceptanceRate: 85,
  },
  {
    id: 'unam-mexico',
    name: 'National Autonomous University of Mexico',
    nameRu: 'Национальный автономный университет Мексики',
    nameKk: 'Мексика ұлттық автономиялық университеті',
    location: 'Mexico City, Mexico',
    locationRu: 'Мехико, Мексика',
    locationKk: 'Мехико, Мексика',
    country: 'Mexico',
    region: 'south-america',
    rank: 121,
    directions: ['science', 'engineering', 'humanities', 'arts'],
    requirements: {
      minGPA: 2.8,
      minIELTS: 5.5,
      minAchievements: 0,
    },
    programs: ['Science', 'Engineering', 'Arts', 'Philosophy'],
    programsRu: ['Наука', 'Инженерия', 'Искусство', 'Философия'],
    programsKk: ['Ғылым', 'Инженерия', 'Өнер', 'Философия'],
    tuitionFee: 'Free',
    acceptanceRate: 92,
  },
  {
    id: 'sdu-kz',
    name: 'Suleyman Demirel University',
    nameRu: 'Университет имени Сулеймана Демиреля',
    nameKk: 'Сүлеймен Демирел атындағы университет',
    location: 'Almaty, Kazakhstan',
    locationRu: 'Алматы, Казахстан',
    locationKk: 'Алматы, Қазақстан',
    country: 'Kazakhstan',
    region: 'central-asia',
    rank: 801,
    directions: ['engineering', 'technology', 'business', 'law'],
    requirements: {
      minGPA: 2.5,
      minIELTS: 5.0,
      minAchievements: 0,
    },
    programs: ['Engineering', 'IT', 'Business', 'Law'],
    programsRu: ['Инженерия', 'ИТ', 'Бизнес', 'Право'],
    programsKk: ['Инженерия', 'ИТ', 'Бизнес', 'Құқық'],
    tuitionFee: '₸1,500,000',
    acceptanceRate: 85,
  },
];

// Direction mapping for filtering
export const DIRECTION_MAPPING: Record<string, string[]> = {
  technology: ['technology', 'engineering'],
  science: ['science', 'medicine'],
  humanities: ['humanities', 'arts', 'law'],
  arts: ['arts', 'humanities'],
  business: ['business'],
  medicine: ['medicine', 'science'],
  engineering: ['engineering', 'technology'],
  law: ['law', 'humanities'],
};